import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-green-600 shadow-sm">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between h-16">
              <div className="flex space-x-8">
                <Link href="/" className="flex items-center px-2 py-2 text-white hover:opacity-50 transition-opacity">
                  首頁
                </Link>
                <Link href="/about" className="flex items-center px-2 py-2 text-white hover:opacity-50 transition-opacity">
                  關於
                </Link>
                <Link href="/todos" className="flex items-center px-2 py-2 text-white hover:opacity-50 transition-opacity">
                  待辦事項
                </Link>
                <Link href="/contact" className="flex items-center px-2 py-2 text-white hover:opacity-50 transition-opacity">
                  聯絡資訊
                </Link>
                <Link href="/chat-room" className="flex items-center px-2 py-2 text-white hover:opacity-50 transition-opacity">
                  聊天室
                </Link>
              </div>
            </div>
          </div>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
